### ISSUE TITLE
--resolution option isn't having an effect

### ISSUE THREAD

**Issue by bravokiloecho** [pmndrs/gltfjsx#177] opened 2023-01-11 15:05 UTC
When I run the command:

```
npx gltfjsx package-30.glb --transform
```

it compresses the model from `28.1MB` to `866KB`. But when I try any different value with the `--resolution` prop like this:

```
npx gltfjsx package-30.glb --transform --resolution=256
```

(or replace `256` with any other number) it still compresses down to `866KB`.

So I'm not sure the `--resolution` prop is having an effect. Am I using it correctly here?

Thank you (and thanks for such an amazing tool)!

**Comment by prometixX** [comment] 2023-01-16 00:57
If I use `--resolution [value]` or `--resolution=[value]` it works.
Maybe you can share your model.

**Comment by bravokiloecho** [comment] 2023-01-17 14:20
Hello! I can't share the model sadly. Are you using the `--resolution` flag with the `--transform` flag?

**Comment by donmccurdy** [comment] 2023-01-26 01:45
Could you check the output of the Texture tables with —

```bash
npm install --global @gltf-transform/cli@next

gltf-transform inspect package-30.glb
```

That would tell you what the texture resolutions are in the output.

**Comment by bravokiloecho** [comment] 2023-02-01 08:47
Thanks for the tip @donmccurdy!

When I run either `npx gltfjsx package-30.glb --transform --resolution=256` or `npx gltfjsx package-30.glb --transform` and inspect the model, the results are the same (texture size of 1024x1024):

```
 TEXTURES
 ────────────────────────────────────────────
┌───┬──────┬─────┬──────────────────────────┬───────────┬────────────┬─────────────┬────────────┬───────────┬──────────┐
│ # │ name │ uri │ slots                    │ instances │ mimeType   │ compression │ resolution │ size      │ gpuSize¹ │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 0 │      │     │ baseColorTexture         │ 1         │ image/jpeg │             │ 1024x1024  │ 66.69 KB  │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 1 │      │     │ baseColorTexture         │ 1         │ image/jpeg │             │ 1024x1024  │ 62.46 KB  │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 2 │      │     │ normalTexture            │ 1         │ image/jpeg │             │ 1024x1024  │ 69.56 KB  │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 3 │      │     │ metallicRoughnessTexture │ 1         │ image/jpeg │             │ 1024x1024  │ 197.31 KB │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 4 │      │     │ baseColorTexture         │ 1         │ image/jpeg │             │ 1024x1024  │ 34.99 KB  │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 5 │      │     │ normalTexture            │ 1         │ image/jpeg │             │ 1024x1024  │ 42.18 KB  │ 5.59 MB  │
├───┼──────┼─────┼──────────────────────────┼───────────┼────────────┼─────────────┼────────────┼───────────┼──────────┤
│ 6 │      │     │ baseColorTexture         │ 1         │ image/jpeg │             │ 1024x1024  │ 36.05 KB  │ 5.59 MB  │
```

**Comment by bravokiloecho** [comment] 2023-02-01 09:10
Another update...

When I cloned this repo and ran it locally, the `--resolution` option worked as expected

**Comment by hakimmazouz** [comment] 2024-11-13 05:36
@bravokiloecho Did this get fixed yet? And how do you get that table view?

**Comment by donmccurdy** [comment] 2024-11-13 14:23
@hakimmazouz the table view comes from https://gltf-transform.dev/cli, with:

```
gltf-transform inspect scene.glb
```

The `--resolution` flag works for me, but no sample models have been shared in this thread, so if it's a model-specific bug then we have no way to know. I'll close this issue, but would be happy to reopen it if the issue is still reproducible and a model can be shared.

**Closed** 2024-11-13 14:24 UTC
